# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='h_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='h_pic_descr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='t_pic',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='t_pic_2',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='t_pic_2_descr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='t_pic_3',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='t_pic_3_descr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='t_pic_4',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='t_pic_4_descr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='t_pic_descr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
