# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171110_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='h_pic_descr',
            new_name='heade_pic_descr',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='h_pic',
            new_name='header_pic',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='t_pic',
            new_name='topic_pic',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='t_pic_2',
            new_name='topic_pic_2',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='t_pic_2_descr',
            new_name='topic_pic_2_descr',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='t_pic_3',
            new_name='topic_pic_3',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='t_pic_3_descr',
            new_name='topic_pic_3_descr',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='t_pic_4',
            new_name='topic_pic_4',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='t_pic_4_descr',
            new_name='topic_pic_4_descr',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='t_pic_descr',
            new_name='topic_pic_descr',
        ),
    ]
