# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171112_1328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Mentee',
        ),
    ]
