# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171112_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page_views',
            field=models.IntegerField(default=0),
        ),
    ]
