# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_page_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='', verbose_name='ads/')),
            ],
        ),
    ]
