# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='owner_status',
            field=models.CharField(choices=[('owner', 'Owner'), ('staff', 'Staff')], default='staff', max_length=300),
        ),
    ]
